### PR TITLE
Fix a memory leak in reifyTypeable (fixes #54)

### LINKED ISSUE #54: Memory leak with `reifyTypeable`
If a value is reified with `reifyTypeable` and then never `reflect`ed, its underlying `StablePtr` is leaked and never freed.

Example reproducer:
```hs
{- cabal:
build-depends: base, reflection
-}

import Control.Exception
import Data.Reflection

go :: Int -> IO ()
go 0 = pure ()
go n = reifyTypeable n $ \p -> do
  --evaluate (reflect p)
  go (n - 1)

main = go 10000000
```
Running this on my machine exhibits `160,031,904 bytes maximum residency (10 sample(s))`. Uncommenting the `evaluate` reduces it to `35,984 bytes maximum residency (1 sample(s))`.

### PR DESCRIPTION
**Pull request by mniip**
Admittedly I am not 100% sure what the point of `reflectBefore` was (does anyone else?)

I strongly suspect it was trying to reinvent `evaluate` out of `return` and `$!`, which I've now replaced with an actual `evaluate $ k p` call.

### CODE REVIEW

File: fast/Data/Reflection.hs [hunk 1]
```diff
@@ -580,11 +588,23 @@ instance (B b0, B b1, B b2, B b3, B b4, B b5, B b6, B b7, w0 ~ W b0 b1 b2 b3, w1
...
--- This had to be moved to the top level, due to an apparent bug in
--- the ghc inliner introduced in ghc 7.0.x
-reflectBefore :: forall (proxy :: * -> *) s b. (Proxy s -> b) -> proxy s -> b
-reflectBefore f = const $! f Proxy
-{-# NOINLINE reflectBefore #-}
+instance Reifies (StableBox w0 w1 a) (Box b) => Reifies (Stable w0 w1 a) b where
+  reflect p = case reflect (stableBox p) of
+    Box a -> a
+
+-- Ensure that exactly one dictionary of Reifies (StableBox ...) is created and evaluated per a reifyTypeable call.
```
Comment (RyanGlScott) [inline fast/Data/Reflection.hs:595]:
```suggestion
-- Ensure that exactly one dictionary of Reifies (StableBox ...) is created and evaluated per reifyTypeable call.
```

File: fast/Data/Reflection.hs [hunk 2]
```diff
@@ -580,11 +588,23 @@ instance (B b0, B b1, B b2, B b3, B b4, B b5, B b6, B b7, w0 ~ W b0 b1 b2 b3, w1
...
+--
+-- Evaluating the dictionary's thunk frees the allocated StablePtr, and the contents of the StablePtr replace the thunk.
+-- Creating two dictionaries would mean a double free upon their evaluation, and leaving a dictionary unevaluated would
+-- leak the StablePtr (see https://github.com/ekmett/reflection/issues/54 ).
```
Comment (RyanGlScott) [inline fast/Data/Reflection.hs:599]:
```suggestion
-- leak the StablePtr (see https://github.com/ekmett/reflection/issues/54).
```

File: fast/Data/Reflection.hs [hunk 3]
```diff
@@ -580,11 +588,23 @@ instance (B b0, B b1, B b2, B b3, B b4, B b5, B b6, B b7, w0 ~ W b0 b1 b2 b3, w1
...
+--
+-- To separate evaluation of the dictionary and evaluation of the actual argument passed to reifyTypeable, we insert a
+-- Box inbetween.
```
Comment (RyanGlScott) [inline fast/Data/Reflection.hs:602]:
```suggestion
-- Box in between.
```

File: slow/Data/Reflection.hs [hunk 4]
```diff
@@ -174,11 +187,33 @@ instance (B b0, B b1, B b2, B b3, B b4, B b5, B b6, B b7)
...
-reflectBefore :: Reifies s a => (Proxy s -> b) -> proxy s -> b
-reflectBefore f = const $! f Proxy
-{-# NOINLINE reflectBefore #-}
+instance Reifies (StableBox b0 b1 b2 b3 b4 b5 b6 b7 a) (Box b)
+    => Reifies (Stable b0 b1 b2 b3 b4 b5 b6 b7 a) b where
+  reflect p = case reflect (stableBox p) of
+    Box a -> a
+
+-- Ensure that exactly one dictionary of Reifies (StableBox ...) is created and
+-- evaluated per a reifyTypeable call.
```
Comment (RyanGlScott) [inline slow/Data/Reflection.hs:196]:
```suggestion
-- evaluated per reifyTypeable call.
```

File: slow/Data/Reflection.hs [hunk 5]
```diff
@@ -174,11 +187,33 @@ instance (B b0, B b1, B b2, B b3, B b4, B b5, B b6, B b7)
...
+--
+-- Evaluating the dictionary's thunk frees the allocated StablePtr, and the
+-- contents of the StablePtr replace the thunk. Creating two dictionaries would
+-- mean a double free upon their evaluation, and leaving a dictionary
+-- unevaluated would leak the StablePtr
+-- (see https://github.com/ekmett/reflection/issues/54 ).
```
Comment (RyanGlScott) [inline slow/Data/Reflection.hs:202]:
```suggestion
-- (see https://github.com/ekmett/reflection/issues/54).
```

File: slow/Data/Reflection.hs [hunk 6]
```diff
@@ -174,11 +187,33 @@ instance (B b0, B b1, B b2, B b3, B b4, B b5, B b6, B b7)
...
+--
+-- To separate evaluation of the dictionary and evaluation of the actual
+-- argument passed to reifyTypeable, we insert a Box inbetween.
```
Comment (RyanGlScott) [inline slow/Data/Reflection.hs:205]:
```suggestion
-- argument passed to reifyTypeable, we insert a Box in between.
```

**Review by RyanGlScott — COMMENTED** [review]
Thanks, @mniip! I pushed a fix for an unrelated issue in the examples.

Other than some minor suggestions below, LGTM.

**Review by RyanGlScott — APPROVED** [review]
